# Generated by Django 5.2.8 on 2025-11-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Include country code, e.g., +254...', max_length=20),
        ),
    ]
