# Generated by Django 5.2.8 on 2025-12-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='whatsapp_number',
        ),
    ]
