# Generated by Django 5.2.8 on 2025-12-07 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_badge_profile_badges_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='badges',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='review',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('BUYER', 'Buyer'), ('SUPPLIER', 'Supplier'), ('RIDER', 'Rider'), ('ADMIN', 'Admin')], default='FARMER', max_length=20),
        ),
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('vehicle_type', models.CharField(choices=[('MOTORBIKE', 'Motorbike'), ('TUKTUK', 'TukTuk'), ('PICKUP', 'Pickup Truck'), ('BICYCLE', 'Bicycle')], default='MOTORBIKE', max_length=20)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
