# Generated by Django 5.2.8 on 2025-12-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('MOTORBIKE', 'Motorbike'), ('TUKTUK', 'TukTuk'), ('PICKUP', 'Pickup Truck'), ('LORRY', 'Lorry/Truck'), ('BICYCLE', 'Bicycle')], default='MOTORBIKE', max_length=20),
        ),
    ]
