# Generated by Django 5.2.8 on 2025-12-07 21:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_average_rating_profile_badge_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riderprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rider Profile', 'verbose_name_plural': 'Rider Profiles'},
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='active_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='active_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='can_handle_fragile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='can_handle_perishable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='constituency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='county',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_speed_kmh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='estate_village',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='failed_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='good_conduct_cert',
            field=models.FileField(blank=True, upload_to='rider_certs/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID number', max_length=20),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='id_photo',
            field=models.ImageField(blank=True, upload_to='rider_ids/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='is_tracking_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='last_payout_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='last_payout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='max_volume_liters',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='max_weight_kg',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='mpesa_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='on_time_delivery_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='pending_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='successful_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='total_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='transport_mode',
            field=models.CharField(choices=[('MOTORBIKE', 'Motorbike'), ('BICYCLE', 'Bicycle'), ('TUKTUK', 'Tuk Tuk'), ('ONFOOT', 'On Foot')], db_index=True, default='MOTORBIKE', max_length=20),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_riders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='works_weekends',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='is_available',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['verification_status', 'is_available'], name='users_rider_verific_07ebfc_idx'),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['county', 'is_available'], name='users_rider_county_94d8e0_idx'),
        ),
    ]
