# Generated by Django 5.2.8 on 2025-12-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_riderprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='riderprofile',
            name='users_rider_verific_07ebfc_idx',
        ),
        migrations.RemoveIndex(
            model_name='riderprofile',
            name='users_rider_county_94d8e0_idx',
        ),
        migrations.RenameField(
            model_name='riderprofile',
            old_name='successful_deliveries',
            new_name='cancelled_deliveries',
        ),
        migrations.RenameField(
            model_name='riderprofile',
            old_name='total_reviews',
            new_name='completed_deliveries',
        ),
        migrations.RenameField(
            model_name='riderprofile',
            old_name='last_payout_date',
            new_name='verified_at',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='can_handle_fragile',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='can_handle_perishable',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='current_speed_kmh',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='good_conduct_cert',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='is_tracking_active',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='last_payout_amount',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='mpesa_number',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='on_time_delivery_rate',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='suspension_reason',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='transport_mode',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='verified_date',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='works_weekends',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='certificate_of_conduct',
            field=models.FileField(blank=True, null=True, upload_to='rider_certificates/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('MOTORBIKE', 'Motorbike'), ('BICYCLE', 'Bicycle'), ('TUKTUK', 'Tuk Tuk'), ('ON_FOOT', 'On Foot')], default='MOTORBIKE', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='active_hours_end',
            field=models.TimeField(blank=True, help_text='e.g., 18:00', null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='active_hours_start',
            field=models.TimeField(blank=True, help_text='e.g., 08:00', null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='constituency',
            field=models.CharField(blank=True, help_text='e.g., Westlands', max_length=100),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='county',
            field=models.CharField(blank=True, help_text='e.g., Nairobi', max_length=100),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='estate_village',
            field=models.CharField(blank=True, help_text='e.g., Highridge', max_length=100),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID or Passport number', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='rider_ids/'),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Currently available for deliveries'),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='max_volume_liters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum volume in liters', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='max_weight_kg',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Maximum weight in kg', max_digits=5),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='pending_payments',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Payments not yet received', max_digits=10),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total lifetime earnings', max_digits=10),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance in KSH', max_digits=10),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='ward',
            field=models.CharField(blank=True, help_text='e.g., Parklands', max_length=100),
        ),
    ]
