# Generated by Django 5.2.8 on 2025-12-08 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_riderprofile_users_rider_verific_07ebfc_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritefarmer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterModelOptions(
            name='riderprofile',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='favoritefarmer',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='badge_awarded_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='successful_deliveries',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_reviews',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_sales',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='certificate_of_conduct',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='county',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='estate_village',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='id_photo',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='last_location_update',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='max_volume_liters',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='max_weight_kg',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='pending_payments',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='total_earnings',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='wallet_balance',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='ward',
        ),
        migrations.AddField(
            model_name='favoritefarmer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_plate_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='active_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='active_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('MOTORBIKE', 'Motorbike'), ('TUKTUK', 'TukTuk'), ('PICKUP', 'Pickup'), ('LORRY', 'Lorry'), ('BICYCLE', 'Bicycle')], default='MOTORBIKE', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
