# Generated by Django 5.2.8 on 2025-12-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_favoritefarmer_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Public name to show (e.g. Farm Name)', max_length=100),
        ),
    ]
