# Generated by Django 5.2.8 on 2025-12-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_name',
            field=models.CharField(blank=True, help_text='For marketplace sellers/businesses', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='buyer_type',
            field=models.CharField(blank=True, choices=[('MARKETPLACE', 'Marketplace Seller'), ('INDIVIDUAL', 'Individual Consumer'), ('RESTAURANT', 'Restaurant/Hotel'), ('RETAILER', 'Retail Shop')], help_text='Type of buyer', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='marketplace_location',
            field=models.CharField(blank=True, help_text='Where your marketplace/business is located', max_length=200),
        ),
    ]
