# Generated by Django 5.2.8 on 2025-12-09 10:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_business_name_profile_buyer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_level', models.CharField(choices=[('BEGINNER', 'Beginner Farmer'), ('BRONZE', 'Bronze Farmer'), ('SILVER', 'Silver Farmer'), ('GOLD', 'Gold Farmer'), ('PLATINUM', 'Platinum Farmer'), ('DIAMOND', 'Diamond Farmer')], default='BEGINNER', max_length=20)),
                ('total_sales', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.OneToOneField(limit_choices_to={'role': 'FARMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_badge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Badge',
                'verbose_name_plural': 'Farmer Badges',
            },
        ),
        migrations.CreateModel(
            name='FarmerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'BUYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_reviews', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'FARMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Review',
                'verbose_name_plural': 'Farmer Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('farmer', 'buyer')},
            },
        ),
    ]
