# Generated by Django 5.2.8 on 2025-12-09 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_farmerbadge_farmerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_farmers',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_buyers', to=settings.AUTH_USER_MODEL),
        ),
    ]
