# Generated by Django 5.2.8 on 2025-12-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_favorite_farmers'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
