# Generated by Django 5.2.8 on 2025-12-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_riderprofile_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
