# Generated by Django 5.2.8 on 2025-12-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_county_profile_county_subcounty_profile_sub_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='verification_good_conduct',
            field=models.ImageField(blank=True, null=True, upload_to='rider_verification/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='verification_id_back',
            field=models.ImageField(blank=True, null=True, upload_to='rider_verification/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='verification_id_front',
            field=models.ImageField(blank=True, null=True, upload_to='rider_verification/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='verification_license',
            field=models.ImageField(blank=True, null=True, upload_to='rider_verification/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='verification_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='rider_verification/'),
        ),
    ]
