# Generated by Django 5.2.8 on 2025-12-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_riderprofile_verification_good_conduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='rider_passports/'),
        ),
    ]
