# Generated by Django 5.2.8 on 2025-12-13 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_riderreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_vehicle_type', models.CharField(blank=True, max_length=20)),
                ('old_vehicle_plate', models.CharField(blank=True, max_length=20)),
                ('old_license_number', models.CharField(blank=True, max_length=50)),
                ('new_vehicle_type', models.CharField(max_length=20)),
                ('new_vehicle_plate', models.CharField(max_length=20)),
                ('new_license_number', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(help_text='Reason for change request')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text="Admin's notes on approval/rejection")),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vehicle_changes', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Change Request',
                'verbose_name_plural': 'Vehicle Change Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
