# Generated by Django 5.2.8 on 2025-12-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_vehiclechangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
