# Generated by Django 5.2.8 on 2025-12-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_riderprofile_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerbadge',
            name='is_manual_override',
            field=models.BooleanField(default=False, help_text='If checked, automatic badge updates will be disabled.'),
        ),
    ]
