# Generated by Django 5.2.8 on 2025-11-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_product_approval_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VEGETABLES', 'Vegetables'), ('FRUITS', 'Fruits'), ('GRAINS_CEREALS', 'Grains & Cereals'), ('LEGUMES_PULSES', 'Legumes & Pulses'), ('HERBS_SPICES', 'Herbs & Spices'), ('CATTLE', 'Cattle'), ('POULTRY', 'Poultry'), ('GOATS_SHEEP', 'Goats & Sheep'), ('PIGS', 'Pigs'), ('FISH_AQUACULTURE', 'Fish & Aquaculture'), ('SEEDS_SEEDLINGS', 'Seeds & Seedlings'), ('FERTILIZERS', 'Fertilizers'), ('PESTICIDES', 'Pesticides & Herbicides'), ('ANIMAL_FEED', 'Animal Feed'), ('MACHINERY', 'Machinery'), ('TOOLS', 'Tools'), ('IRRIGATION', 'Irrigation Equipment'), ('DAIRY', 'Dairy Products'), ('HONEY', 'Honey & Bee Products'), ('PROCESSED_FOODS', 'Processed Foods'), ('ORGANIC', 'Organic Products'), ('FLOWERS', 'Flowers & Ornamentals'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
