# Generated by Django 5.2.8 on 2025-11-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_product_category_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VEGETABLES', 'Vegetables'), ('FRUITS', 'Fruits'), ('GRAINS_CEREALS', 'Grains & Cereals'), ('LEGUMES_PULSES', 'Legumes & Pulses'), ('LIVESTOCK_POULTRY', 'Livestock & Poultry'), ('DAIRY_PRODUCTS', 'Dairy Products'), ('SEEDS_SEEDLINGS', 'Seeds & Seedlings'), ('FERTILIZERS_SOIL', 'Fertilizers & Soil'), ('PESTICIDES_CHEMICALS', 'Pesticides & Chemicals'), ('FARM_EQUIPMENT', 'Farm Equipment & Tools'), ('IRRIGATION_SYSTEMS', 'Irrigation Systems'), ('ANIMAL_FEED', 'Animal Feed'), ('HERBS_SPICES', 'Herbs & Spices'), ('ORGANIC_PRODUCTS', 'Organic Products'), ('PROCESSED_FOODS', 'Processed Foods'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
