# Generated by Django 5.2.8 on 2025-11-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_product_category_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VEGETABLES', 'Vegetables'), ('FRUITS', 'Fruits'), ('GRAINS', 'Grains'), ('LIVESTOCK', 'Livestock'), ('POULTRY', 'Poultry'), ('DAIRY', 'Dairy'), ('SEEDS', 'Seeds'), ('FERTILIZERS', 'Fertilizers'), ('EQUIPMENT', 'Equipment'), ('FLOWERS', 'Flowers'), ('HERBS', 'Herbs'), ('SPICES', 'Spices'), ('HONEY', 'Honey'), ('FISH', 'Fish'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
