# Generated by Django 5.2.8 on 2025-12-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_remove_order_amount_paid_order_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='kg', help_text='e.g. kg, litre, crate, tray, piece', max_length=50),
        ),
    ]
