# Generated by Django 5.2.8 on 2025-12-07 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_product_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('FARMER_DELIVERY', 'Farmer Delivers'), ('RIDER_DELIVERY', 'Rider Delivery')], default='FARMER_DELIVERY', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_ACCEPTED', 'Order Accepted'), ('ORDER_REJECTED', 'Order Rejected'), ('RIDER_ASSIGNED', 'Rider Assigned'), ('ORDER_PICKED_UP', 'Order Picked Up'), ('ORDER_DELIVERED', 'Order Delivered')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('ESCROW', 'Escrow (Paid)'), ('IN_DELIVERY', 'In Delivery'), ('DELIVERED', 'Delivered'), ('PAID_OUT', 'Paid Out to Farmer'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
