# Generated by Django 5.2.8 on 2025-12-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_order_assigned_rider_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_ACCEPTED', 'Order Accepted'), ('ORDER_REJECTED', 'Order Rejected'), ('DELIVERY_REQUEST', 'Delivery Request'), ('RIDER_ASSIGNED', 'Rider Assigned'), ('ORDER_PICKED_UP', 'Order Picked Up'), ('ORDER_DELIVERED', 'Order Delivered')], max_length=20),
        ),
    ]
