# Generated by Django 5.2.8 on 2025-12-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_ACCEPTED', 'Order Accepted'), ('ORDER_REJECTED', 'Order Rejected'), ('ORDER_ASSIGNED', 'Order Assigned')], max_length=20),
        ),
    ]
