# Generated by Django 5.2.8 on 2025-12-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('ESCROW', 'Escrow (Paid)'), ('IN_DELIVERY', 'In Delivery'), ('DELIVERED', 'Delivered'), ('PAID_OUT', 'Paid Out to Farmer'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
