# Generated by Django 5.2.8 on 2025-12-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_product_freshness_notes_product_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_verification_code',
            field=models.CharField(blank=True, help_text='Code buyer scans/enters to confirm delivery', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_ready_for_pickup',
            field=models.BooleanField(default=False, help_text='Marked by farmer when ready for rider'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_verification_code',
            field=models.CharField(blank=True, help_text='Code rider scans/enters to confirm pickup', max_length=6, null=True),
        ),
    ]
