# Generated by Django 5.2.8 on 2025-12-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_order_delivery_fee_order_delivery_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.CharField(blank=True, help_text='E.g. 30 mins', max_length=50, null=True),
        ),
    ]
