# Generated by Django 5.2.8 on 2025-12-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_order_delivery_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('PICKUP', 'Pickup (Buyer collects)'), ('DELIVERY', 'Delivery (Rider needed)')], default='PICKUP', max_length=20),
        ),
    ]
