# Generated by Django 5.2.8 on 2025-12-14 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_order_delivery_method'),
        ('users', '0028_vehiclechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, help_text="Buyer's delivery address for this order", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.deliveryaddress'),
        ),
    ]
