# Generated by Django 5.2.8 on 2025-12-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
