# Generated by Django 5.2.8 on 2025-12-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_comment_is_edited_comment_likes_comment_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
    ]
