# Generated by Django 5.2.8 on 2025-12-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Is this post flagged for review?'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_pest_alert',
            field=models.BooleanField(default=False, help_text='Is this a pest/disease alert?'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='community_videos/'),
        ),
    ]
